name: Merge remote repos to main

on:
  schedule:
    - cron: '0 2 * * *'   # daily at 02:00 UTC
  workflow_dispatch:

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Replace folders in OpenPanel repo
        shell: bash
        run: |
         
          # Clean existing folders
          git rm -r --cached tests translations configuration opencli integrations/fossbilling integrations/paymenter.org integrations/whmcs integrations/cpanel-import integrations/cyberpanel-import integrations/virtualizor || true
          rm -rf tests translations configuration opencli integrations/fossbilling integrations/paymenter.org integrations/whmcs integrations/cpanel-import integrations/cyberpanel-import integrations/virtualizor

          # Clone replacements
          git clone --depth=1 https://github.com/stefanpejcic/openpanel-tests tests-tmp
          git clone --depth=1 https://github.com/stefanpejcic/openpanel-translations translations-tmp
          git clone --depth=1 https://github.com/stefanpejcic/openpanel-configuration configuration-tmp
          git clone --depth=1 https://github.com/stefanpejcic/opencli opencli-tmp
          
          git clone --depth=1 https://github.com/stefanpejcic/cPanel-to-OpenPanel cpanel-tmp
          git clone --depth=1 https://github.com/stefanpejcic/CyberPanel-to-OpenPanel cyberpanel-tmp
          git clone --depth=1 https://github.com/stefanpejcic/openpanel-whmcs-module whmcs-tmp
          git clone --depth=1 https://github.com/stefanpejcic/openpanel-virtualizor virtualizor-tmp
          git clone --depth=1 https://github.com/stefanpejcic/openpanel-paymenter.org paymenter-tmp
          git clone --depth=1 https://github.com/stefanpejcic/FOSSBilling-OpenPanel fossbilling-tmp

          # Move contents only (not the .git folder)
          mv tests-tmp tests
          mv translations-tmp translations
          mv configuration-tmp configuration
          mv opencli-tmp opencli
          
          mv cpanel-tmp integrations/cpanel-import
          mv cyberpanel-tmp integrations/cyberpanel-import
          mv whmcs-tmp integrations/whmcs
          mv virtualizor-tmp integrations/virtualizor
          mv paymenter-tmp integrations/paymenter.org
          mv fossbilling-tmp integrations/fossbilling

          rm -rf tests/.git translations/.git configuration/.git configuration/.github opencli/.git opencli/.github  integrations/cpanel-import/.git integrations/cyberpanel-import/.git integrations/whmcs/.git /integrations/virtualizor/.git integrations/paymenter.org/.git integrations/fossbilling/.git

          git config user.name "stefanpejcic"
          git config user.email "stefan@pejcic.rs"

          git add translations configuration opencli integrations tests
          if ! git diff --cached --quiet; then
            git commit -m "chore: sync folders from upstream"
            git push origin main
          else
            echo "No changes to commit."
          fi
